{% set version = "2.9" %}
package:
  name: bash-completion
  version: "{{ version }}"

source:
  git_rev: "{{ version }}"
  git_url: https://github.com/scop/bash-completion
  patches:
    - completions-path.patch

build:
  number: 5

requirements:
  build:
    - autoconf
    - automake

## These have hard to meet dependencies and take along time to run
# test:
#   commands:
#     - make check

about:
  home: https://github.com/scop/bash-completion
  license: GPL2
  license_file: COPYING
  summary: "Programmable completion functions for bash."

# vim:set ts=8 sw=2 sts=2 tw=78 et:
