{% set version = "2.9" %}
package:
  name: bash-completion
  version: "{{ version }}"

source:
  git_rev: "{{ version }}"
  git_url: https://github.com/scop/bash-completion
  patches:
    # bug in upstream which will be fixed by release 2.10
    - sysvdirs.patch

    # add a conda specific library loaded flag
    - track-conda-loaded.patch

    # search for completions in the conda environment
    - completions-path.patch

    # adjust double load trap to use conda specific
    - double-load-trap.patch

build:
  number: 9

requirements:
  build:
    - autoconf
    - automake

## These have hard to meet dependencies and take along time to run
# test:
#   commands:
#     - make check

about:
  home: https://github.com/scop/bash-completion
  license: GPL2
  license_file: COPYING
  summary: "Programmable completion functions for bash."

# vim:set ts=8 sw=2 sts=2 tw=78 et:
